api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    oauth:
        enabled: true
        clientId: '%env(API_PLATFORM_OAUTH_DEV_CLIENT_ID)%'
        clientSecret: '%env(API_PLATFORM_OAUTH_DEV_CLIENT_SECRET)%'
        type: oauth2
        flow: application
        tokenUrl: /oauth/v2/token
        authorizationUrl: /oauth/v2/auth
        scopes: {  }


