main:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: api_doc

authentication_token:
    path: /api/authentication_token
    methods: ['POST']
